### ISSUE TITLE
Unable to generate nested oneOf

### ISSUE THREAD

**Issue by eldjuve** [jhannes/openapi-generator-java-annotationfree#10]
With nested operators, say (pasudo yaml):
```
command: 
  oneOf:
    - ref: badCommand
    - ref: goodCommand
  badCommand:
     oneOf:
        -ref: someBadCommand
        -ref: someOtherBadCommand
      discriminator:
        propertyName: type
  someBadCommand:
     properties:
        type:
          enum: [ThisIsReallyBadCommand]
...
```
The generator is unable to generate the top type/class. Possible workaround would be to inline the top oneOf
